import { APP_NAME } from './constants'
import { formatCents } from './pricing'

/**
 * Renders the monthly rent agreement.
 *
 * ⚠️ SPECIMEN TEMPLATE — NOT LEGAL ADVICE. Vehicle advertising touches motor
 * insurance, local signage rules, tax treatment of the driver's income, and in
 * some jurisdictions commercial-vehicle registration. A lawyer must review this
 * before anyone relies on it. The UI carries the same warning.
 *
 * The output is snapshotted onto the Agreement row at generation time, so later
 * edits to this template can never alter an already-executed agreement.
 */

export type AgreementVars = {
  driverName: string
  driverPhone: string | null
  advertiserName: string
  campaignName: string
  vehicle: string
  /** Masked plate — the full plate is never written into the contract body. */
  plateMasked: string
  panelLabel: string
  panelWidthCm: number
  panelHeightCm: number
  monthlyRentCents: number
  termMonths: number
  totalValueCents: number
  driverPayoutCents: number
  startDate: Date
  endDate: Date
  creativeName: string
}

const d = (date: Date) =>
  date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

export function renderAgreement(v: AgreementVars): string {
  const monthlyPayout = Math.round(v.driverPayoutCents / v.termMonths)

  return `# Vehicle Panel Advertising Rent Agreement

**Specimen template — not legal advice.** This document is generated by ${APP_NAME}, a
prototype. It has not been reviewed by a lawyer and must not be relied upon as an
executed contract without independent legal review.

---

## 1. Parties

| | |
|---|---|
| **Driver (space provider)** | ${v.driverName}${v.driverPhone ? ` · ${v.driverPhone}` : ''} |
| **Advertiser (space renter)** | ${v.advertiserName} |
| **Campaign** | ${v.campaignName} |
| **Platform** | ${APP_NAME} (facilitator; not a party to the rental itself) |

## 2. The space being rented

| | |
|---|---|
| **Vehicle** | ${v.vehicle} |
| **Registration** | ${v.plateMasked} *(masked; full plate held by the platform for verification)* |
| **Panel** | ${v.panelLabel} |
| **Approximate printable area** | ${v.panelWidthCm} × ${v.panelHeightCm} cm |
| **Artwork** | ${v.creativeName} |

The Driver rents the single body panel named above. No other surface of the vehicle is
included, and this agreement grants no right to the vehicle's interior or its use.

## 3. Term and rent

| | |
|---|---|
| **Start date** | ${d(v.startDate)} |
| **End date** | ${d(v.endDate)} |
| **Term** | ${v.termMonths} month${v.termMonths === 1 ? '' : 's'} |
| **Monthly rent** | ${formatCents(v.monthlyRentCents)} |
| **Total contract value** | ${formatCents(v.totalValueCents)} |
| **Driver receives (monthly)** | ${formatCents(monthlyPayout)} |
| **Driver receives (total)** | ${formatCents(v.driverPayoutCents)} |

The difference between the rent and the Driver's payout is the platform's fee, which
covers printing, shipping, and payment handling.

> In this prototype no money actually moves. All amounts are simulated ledger entries.

## 4. Installation and removal

1. The platform arranges printing and delivery of the decal to the Driver.
2. The Driver applies the decal to the named panel within **14 days** of receipt, on a
   clean and dry surface, and confirms installation in the app.
3. The Driver keeps the decal reasonably clean and visible, and does not obscure it.
4. At the end of the term the Driver removes the decal within **14 days**. Removal of a
   correctly applied vinyl decal does not damage factory paint in sound condition.
5. If the decal is damaged, lost, or peels, the Driver notifies the platform, which
   supplies a replacement at no cost to the Driver.

## 5. Vehicle condition

1. The Driver confirms the named panel is free of rust, active damage, or unrepaired
   accident damage at the start of the term.
2. The Advertiser accepts the vehicle as shown in the verification photographs.
3. The Driver is not responsible for paint defects that existed before installation. The
   Advertiser is not responsible for paint damage arising from pre-existing defects.

## 6. Use of the vehicle

1. The Driver continues to use the vehicle normally and is under **no obligation to drive
   any particular route, distance, or schedule**.
2. Impression estimates shown on the platform are modelled from the Driver's stated
   commute. They are estimates only, and neither the Driver nor the platform guarantees
   any level of exposure, reach, or advertising result.
3. The Driver must not use the vehicle unlawfully while carrying the advertisement.

## 7. Content

1. The Advertiser warrants it holds all rights to the artwork and that the artwork is
   lawful and not misleading.
2. The Driver may refuse artwork they find objectionable before installation, and may
   terminate under clause 9 if artwork is changed to something they object to.
3. The artwork may not imply the Driver personally endorses the product.

## 8. Measurement

Each decal carries a unique QR code. Scans are recorded by the platform and reported to
the Advertiser. Scan counts measure engagement only, and are not a count of impressions.

## 9. Early termination

1. Either party may terminate with **30 days'** written notice.
2. If the Advertiser terminates early, rent is owed up to the end of the notice period.
3. If the Driver terminates early or removes the decal without cause, rent stops on the
   removal date and no further payment is due.
4. If the vehicle is sold, written off, or off the road for more than 30 consecutive
   days, either party may terminate immediately and rent is prorated to that date.

## 10. Insurance, tax, and local rules — Driver to verify

**The Driver is responsible for confirming, before installation, that:**

1. Their motor insurer permits paid advertising on the vehicle. Some policies treat it as
   commercial use and it may affect cover.
2. Carrying paid advertising does not require commercial-vehicle registration or a permit
   where they live.
3. Their lease, finance agreement, employer, homeowners' association, or building rules do
   not prohibit vehicle advertising.
4. They understand rent received may be taxable income and is their responsibility to
   declare.

The platform does not provide insurance, tax, or legal advice, and none of these points
have been verified on the Driver's behalf.

## 11. Liability

The platform acts only as an intermediary. It is not liable for damage to the vehicle,
for the Advertiser's content, for any advertising outcome, or for the parties' compliance
with clause 10. Nothing in this agreement excludes liability that cannot lawfully be
excluded.

## 12. Signatures

By signing in the app, each party confirms they have read this agreement, have authority
to enter into it, and accept its terms.

| | | |
|---|---|---|
| **Driver** | ${v.driverName} | ______________________ |
| **Advertiser** | ${v.advertiserName} | ______________________ |
`
}
