import Link from 'next/link'
import { notFound,redirect } from 'next/navigation'
import { Notice } from '@/components/Notice'
import { Vehicle3DWorkbench } from '@/components/Vehicle3DWorkbench'
import { ProductionHandoff } from '@/components/ProductionHandoff'
import { minimumBidCents } from '@/lib/auction'
import { prisma } from '@/lib/db'
import { formatCents } from '@/lib/pricing'
import { requireRole } from '@/lib/session'
import { getVehicleTemplate } from '@/lib/vehicleTemplates'

export default async function ListingDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){
 const user=await requireRole('ADVERTISER').catch(()=>null);if(!user)redirect('/login')
 const listing=await prisma.panelListing.findUnique({where:{id:(await params).id},include:{panelType:true,vehicle:{include:{commute:true,driver:true}},bids:{orderBy:{createdAt:'desc'},include:{advertiser:true}},creativePlacements:{where:{creative:{campaign:{advertiserId:user.id}}}}}});if(!listing)notFound()
 const campaigns=await prisma.campaign.findMany({where:{advertiserId:user.id,status:'ACTIVE',panelTargets:{some:{panelTypeCode:listing.panelTypeCode}}},include:{creatives:true}});const creatives=campaigns.flatMap(c=>c.creatives);const resolved=getVehicleTemplate({make:listing.vehicle.make,model:listing.vehicle.model,year:listing.vehicle.year,bodyType:listing.vehicle.bodyType});const initial=listing.creativePlacements[0]
 return <div className="flex flex-col gap-6"><div><Link className="text-sm underline" href="/advertise">← Available panels</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">3D placement studio</p><h1 className="text-3xl font-black uppercase">{listing.vehicle.year} {listing.vehicle.make} {listing.vehicle.model}</h1><p className="muted">{listing.panelType.label} · {listing.vehicle.commute?.homeLabel} → {listing.vehicle.commute?.workLabel}</p></div><div className="text-right"><p className="font-mono text-3xl font-bold">{formatCents(listing.currentRentCents)}</p><p className="text-sm muted">monthly · {listing.termMonths} month term</p></div></div></div><Notice {...await searchParams}/>{resolved.template?<Vehicle3DWorkbench template={resolved.template} matchType={resolved.matchType} panelCode={listing.panelTypeCode} creatives={creatives} listingId={listing.id} initial={initial?{creativeId:initial.creativeId,scale:initial.scale,offsetX:initial.offsetX,offsetY:initial.offsetY,rotation:initial.rotation}:undefined}/>:<div className="card p-8">3D preview unavailable. Bidding remains available.</div>}{initial&&<ProductionHandoff placementId={initial.id} widthCm={listing.panelType.widthCm} heightCm={listing.panelType.heightCm} scale={initial.scale} rotation={initial.rotation} creative={creatives.find(c=>c.id===initial.creativeId)}/>}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="card p-5"><h2 className="font-bold">Bid history</h2><div className="table-scroll mt-3"><table className="data"><thead><tr><th>Bidder</th><th>Monthly bid</th><th>Status</th><th>Time</th></tr></thead><tbody>{listing.bids.map(b=><tr key={b.id}><td>{b.advertiser.name}</td><td>{formatCents(b.monthlyAmountCents)}</td><td>{b.status}</td><td>{b.createdAt.toLocaleString()}</td></tr>)}</tbody></table></div></section><aside className="card p-5"><h2 className="font-bold">Place a bid</h2>{campaigns.map(c=>c.creatives[0]&&<form className="mt-3 border-t pt-3" style={{borderColor:'var(--line)'}} key={c.id} action="/api/workflow/bid" method="post"><input type="hidden" name="listingId" value={listing.id}/><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="creativeId" value={c.creatives[0].id}/><label><span className="label">{c.name} · monthly amount</span><input className="input" type="number" name="monthlyAmountCents" min={minimumBidCents(listing.currentRentCents)} defaultValue={minimumBidCents(listing.currentRentCents)}/></label><button className="btn btn-primary mt-2 w-full">Place bid</button></form>)}{campaigns.length===0&&<p className="mt-2 text-sm muted">Create an active campaign targeting this panel first.</p>}</aside></div></div>
}
