import { redirect } from 'next/navigation'
import Link from 'next/link'
import { Notice } from '@/components/Notice'
import { prisma } from '@/lib/db'
import { formatCents } from '@/lib/pricing'
import { requireRole } from '@/lib/session'

export default async function CampaignsPage({searchParams}:{searchParams:Promise<{ok?:string;error?:string}>}) {
  const user=await requireRole('ADVERTISER').catch(()=>null); if(!user) redirect('/login?next=/advertise/campaigns')
  const [brand,panels,cities,campaigns]=await Promise.all([prisma.brand.findUnique({where:{ownerId:user.id},include:{products:true}}),prisma.panelType.findMany({orderBy:{sortOrder:'asc'}}),prisma.city.findMany({orderBy:{name:'asc'}}),prisma.campaign.findMany({where:{advertiserId:user.id},include:{panelTargets:{include:{panelType:true}},_count:{select:{bids:true}}},orderBy:{createdAt:'desc'}})])
  const notice=await searchParams
  return <div className="flex flex-col gap-5"><h1 className="text-2xl font-bold">Campaigns</h1><Notice {...notice}/>{brand?.products[0]&&<form className="card grid gap-3 p-5 sm:grid-cols-2" action="/api/workflow/create-campaign" method="post"><h2 className="font-bold sm:col-span-2">New campaign</h2><input type="hidden" name="productId" value={brand.products[0].id}/><label><span className="label">Name</span><input className="input" name="name" required/></label><label><span className="label">Budget (cents)</span><input className="input" type="number" min="1000" name="budgetCents" defaultValue="100000" required/></label><label><span className="label">Target city</span><select className="select" name="targetChoice">{cities.map(c=><option value={`${c.name}, ${c.region}|${c.lat}|${c.lng}`} key={c.id}>{c.name}, {c.region}</option>)}</select><input type="hidden" name="targetLabel" value={cities[0]?`${cities[0].name}, ${cities[0].region}`:''}/><input type="hidden" name="targetLat" value={cities[0]?.lat}/><input type="hidden" name="targetLng" value={cities[0]?.lng}/></label><label><span className="label">Radius (km)</span><input className="input" type="number" name="targetRadiusKm" defaultValue="40"/></label><label><span className="label">Landing URL</span><input className="input" type="url" name="landingUrl" defaultValue={brand.website??''} required/></label><label><span className="label">Duration (days)</span><input className="input" type="number" name="termDays" defaultValue="90"/></label><div className="sm:col-span-2"><span className="label">Target panels</span><div className="flex flex-wrap gap-3">{panels.map(p=><label className="text-sm" key={p.code}><input type="checkbox" name="panelTypeCodes" value={p.code}/> {p.label}</label>)}</div></div><button className="btn btn-primary justify-self-start">Create campaign</button></form>}
    <div className="card table-scroll"><table className="data"><thead><tr><th>Campaign</th><th>Status</th><th>Budget</th><th>Spent</th><th>Targets</th><th>Bids</th><th></th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.status}</td><td>{formatCents(c.budgetCents)}</td><td>{formatCents(c.spentCents)}</td><td>{c.panelTargets.map(t=>t.panelType.label).join(', ')}</td><td>{c._count.bids}</td><td><Link className="underline" href={`/advertise/campaigns/${c.id}`}>Dashboard</Link></td></tr>)}</tbody></table></div></div>
}
