import { artworkDpi } from '@/lib/vehicle3d'
import { checkPlotterFit, DEFAULT_PLOTTER } from '@/lib/plotterProfiles'

export function ProductionHandoff({placementId,widthCm,heightCm,scale,rotation,creative}:{placementId:string;widthCm:number;heightCm:number;scale:number;rotation:number;creative?:{fileName:string;widthPx:number;heightPx:number}}){
  const fit=checkPlotterFit(widthCm,heightCm)
  const dpi=creative?artworkDpi(creative.widthPx,creative.heightPx,widthCm*scale,heightCm*scale):null
  return <section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Production handoff</p><h2 className="text-xl font-bold">Ready for {DEFAULT_PLOTTER.label}</h2><p className="mt-1 text-sm muted">Operator preflight is required before material is committed.</p></div><span className={`badge ${fit.fits?'badge-good':'badge-warn'}`}>{fit.fits?'Machine width passed':'Machine width blocked'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Finished panel" value={`${widthCm} × ${heightCm} cm`}/><Fact label="PDF with bleed" value={`${widthCm+1} × ${heightCm+1} cm`}/><Fact label="Roll orientation" value={`${fit.crossRollMm} mm across · ${fit.feedLengthMm} mm feed`}/><Fact label="Artwork" value={creative?`${creative.widthPx} × ${creative.heightPx}px · ${dpi?.effectiveDpi} DPI`:'Creative unavailable'}/></div><div className="mt-4 grid gap-3 border-t pt-4 text-sm lg:grid-cols-[1fr_auto]" style={{borderColor:'var(--line)'}}><div><p><strong>Saved placement:</strong> {(scale*100).toFixed(0)}% scale · {(rotation*180/Math.PI).toFixed(1)}° rotation{creative?` · ${creative.fileName}`:''}</p><p className="mt-1 muted">Before printing: confirm actual vehicle measurement, loaded vinyl width, ICC profile, CMYK ink limits, pass mode, heater temperatures, nozzle test, laminate and 100% RIP scale.</p></div><div className="flex flex-wrap gap-2"><a className="btn btn-secondary" href={`/api/print/${placementId}`}>Download print PDF</a><a className="btn btn-primary" target="_blank" rel="noreferrer" href={`/api/print/${placementId}?mode=inline`}>Open plotter print</a></div></div></section>
}

function Fact({label,value}:{label:string;value:string}){return <div className="border-l-4 pl-3" style={{borderColor:'var(--signal)'}}><p className="label">{label}</p><p className="font-mono text-sm font-bold">{value}</p></div>}
