import { Notice } from '@/components/Notice'
import { prisma } from '@/lib/db'
import { createDueSpotChecks } from '@/lib/trust'

export default async function Installations({searchParams}:{searchParams:Promise<{ok?:string;error?:string}>}){
  await createDueSpotChecks()
  const rows=await prisma.installation.findMany({include:{agreement:{include:{campaign:true}},listing:{include:{panelType:true,vehicle:true}},checks:{include:{proof:true},orderBy:{requestedAt:'desc'}},_count:{select:{scans:true}}},orderBy:{createdAt:'desc'}})
  return <div><h1 className="text-2xl font-bold">Fulfilment and proof</h1><p className="mt-1 text-sm muted">Rent eligibility follows verified installation, not QR scan volume.</p><div className="mt-4"><Notice {...await searchParams}/></div><div className="mt-5 flex flex-col gap-4">{rows.map(x=>{const current=x.checks[0];return <article className="card p-5" key={x.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{x.agreement.campaign.name}</h2><p className="text-sm muted">{x.listing.vehicle.make} {x.listing.vehicle.model} · {x.listing.panelType.label} · {x._count.scans} QR engagements</p></div><span className={`badge ${x.status==='VERIFIED'?'badge-good':'badge-warn'}`}>{x.status.replaceAll('_',' ')}</span></div>{current&&<div className="mt-3 rounded-lg p-3" style={{background:'var(--canvas)'}}><p className="text-sm"><strong>{current.type.replaceAll('_',' ')}</strong> · {current.challengeCode} · {current.status}</p>{current.proof&&<div className="mt-3 flex flex-wrap items-end gap-3"><img className="h-32 w-48 rounded object-cover" src={`/api/proofs/${current.proof.id}`} alt="Private installation proof"/><form action="/api/workflow/review-proof" method="post" className="flex gap-2"><input type="hidden" name="proofId" value={current.proof.id}/><button className="btn btn-primary" name="decision" value="APPROVED">Approve</button><button className="btn btn-secondary" name="decision" value="REJECTED">Reject</button></form></div>}</div>}<form className="mt-3 flex gap-2" action="/api/workflow/request-proof" method="post"><input type="hidden" name="installationId" value={x.id}/><button className="btn btn-secondary" name="type" value={x.verifiedAt?'SPOT_CHECK':'INITIAL'}>{x.verifiedAt?'Request spot-check':'Request installation proof'}</button></form>{x.nextCheckAt&&<p className="mt-2 text-xs muted">Next randomized check window begins {x.nextCheckAt.toLocaleDateString()}.</p>}</article>})}</div></div>
}
